---
output: 
  pdf_document:
    citation_package: natbib
    toc: false
    number_sections: false
    keep_tex: true
    fig_caption: true
    template: ../templates/gsingh-HCI.tex
title: "Designing with the Mind in Mind"
subtitle: "Chapters 10, 11 and 12"
subsubtitle: "Reading Summary"

runhead: "Reading Summary"
author:
- name: Gurpreet Singh
  affiliation: CS4474
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontsize: 11pt
indent: yes
colorlinks: true
---

# Chapter 10

## Learning From Experience

### Three Brains

The old brain categorizes everything into edible, dangerous, or sexy and
regulates the body's automatic functions. The mid brain controls emotions and
reactions to events. The new brain controls conscious activity including
planning. 

When we run into a situation, all three brains decide how we react and our
actions. The old brain and mid brain react faster than the new brain.

### Learning from Experience is Easy

People learn from their daily experiences without knowing that they are
learning. Some problems with learning from experience are listed next.Complex
situations with lots of variables are hard to learn from because they do not
occur as often as other experiences. 

Real life experiences are more valuable to the brain then ones you read or hear
about. If something has happened to you or your family member, you will
remember it better.

You may not learn the correct lesson from an experience if you made the wrong
decision at the time of the event. You are not always able to remember the
correct decision if the event occurred again.

People often overgeneralize. If you have only seen dangerous animals that are
black, you will think all dangerous animals are black. This can be seen as
a con or a pro because overgeneralization allows humans to make assumptions
about things they havent seen before which could save their life and help
evolution.

### Performing learned actions is easy

When we do something many times we can do it without thinking. Real world tasks
have a mixture of automatic and controlled components because without the mix
we wouldn't be able to process everything at once. We need automatic activities
to assist us.

### Problem Solving and Calculation are Hard

New problems are hard to solve. Having a large new brain helps us solve these
problems. Problem solving requires focus and is slow. Executes slowly and serially.
Our brains are not optimized for calculation because numbers are so new. We need 
external memory aids to solve complex problems because we use them like extra
working memory.

### Implications for UI design

- Indicate system status and how far user is to goal

- Guide users toward the goal

- Tell users instructions and make them exact

- Don't make users diagnose system problems

- Minimize number of settings

- Minimize calculation (Use graphs)

- Make system similar to something user is used to

# Chapter 11

## Many Factors Assist Learning

### Learn faster when task is consistent

The gap between what the user wants and what a tool provides is called the
"gulf of execution". The smaller the gulf of execution the less the users need
to think about the tool. Design the tool to provide exactly what the user wants
to do

- Perform a task analysis

- Design task focused conceptual model

- Design UI based on conceptual model

A task analysis answers questions about what the user wants to do with the
software and which tasks are most important/frequent.

### Object / Action Analysis

Specifies all the conceptual objects that an application will expose to the
user. Basically a UML diagram for UI objects.

Aim to simplify this with the least amount of concepts and actions the user has
to remember.

Interactive systems should aim to be consistent. More consistent they are the
faster the user can begin using automatic actions inside of the software

You can make a matrix with Objects on Y and Actions on X and find out which
interactions are being done the most to optimize the usage patterns

### Learn faster when vocab is task-focused

Keeping terminology related to the task the user is trying to finish minimizes
the time a user needs to learn how to use the software. Use easier words that
non CS people can understand. Public instead of DB and private instead of
local. Use words that are seen by many people often. Use similar words around
the whole software so the user has to learn less.

### Learn faster when Risk is Low

When there is not much to lose the user will be more inclined to click around
and explore the software. If the user is scared of messing something up they
wont click on anything they arnt used to seeing the result of. Make easily
approachable UIs

# Chapter 12

## Time Requirements Exist

### Responsivness defined

Responsiveness is how quickly a system responds to the user's interactions.
A system can be responsive even with poor performance. You should use callbacks
to let the UI continue operating and let the user know that something will finish.
When a system isnt responsive it cant meet the time deadlines of the human. 

### Time constraints for the human brain 

1 milisecond is the shortest amount of silence you can detect. 5 miliseconds is
the shortest amount of time you can see a visual change to be effected by it 80
miliseconds is how long it takes you to flinch to something. Then it takes 100
miliseconds to fully process something you have seen. Your system has to react
to an action within 140 miliseconds (1.4 seconds) for the user to understand
that their action had an effect on your system. Your attention takes 500
miliseconds to reset from one item to the next. It takes 700 miliseconds to do
a motor action after observing something visual. Any gap in conversation longer
than 1 second is awkward.  A sub-mental task can take up to a maximum of
10 seconds.

Interactive systems need to keep the above constraints in mind when engineering.

### HCI implications

The guidelines for this chapter are:

- React to user interactions instantly
- Indicate background processing 
- Use callbacks and dont hold UI in focus when processing
- Animate smoothly
- Allow users to cancel processing
- provide a ETA for processing 

Additional implications include
- use busy indicators (spinning circles and loading bars)
- Know when it is allowed to use a delay and when it will bother the user
  (sometimes its acceptable if they are doing something hard)
- Display important data first and avoid delays by prompting for extra
  information instead of preprocessing everything for viewing
- When the user is not doing anything directly, you can process information in
  the background and be ready for the next actions the user may take 
- Monitor how long your application has taken and if it falls into an
  acceptable time duration
