---
output: 
  pdf_document:
    citation_package: natbib
    toc: false
    number_sections: false
    keep_tex: true
    fig_caption: true
    template: ../templates/gsingh-HCI.tex
title: "Designing with the Mind in Mind"
subtitle: "Chapters 4, 5 and 6"
subsubtitle: "Reading Summary"

runhead: "Reading Summary"
author:
- name: Gurpreet Singh
  affiliation: CS4474
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontsize: 11pt
indent: yes
colorlinks: true
---

# Chapter 4

## Reading is Unnatural

### Wired for Language not Reading

We are born to speak languages and learn to speak quickly in our childhood but
when we get older it is as difficult as any other skill A different brain area
is used for this type of learning after childhood. Most people learn how to
speak but some people never learn how to read. People may not be good at
reading because of {basically my problems irl}

Reading is teaching our brains how to recognize patterns. Morphemes are
combinations of letters we recognize and put together to make words

### Feature driven vs context driven

Feature driven is bottom up and sometimes called "context free". It starts by
identifying simple features like lines and uses them to make complex objects
like words. This type of reading is faster than context driven despite
instinct.

Context driven is top down and opposite of feature driven. You recognize
a morpheme, word or sentence and treat it like a single object to get it's
meaning. An example of this is something you would read often. Mainly a backup
method for reading.

### Skilled vs Unskilled reading

"Skilled readers" use feature driven mostly and fallback to context driven
"Unskilled readers" use context driven because feature driven is slow for them.

Not enough experience reading as a child causes unskilled reading

### Poor information design disprupts reading

Poor presentation can block reading for unskilled readers. The following are
things that disrupt reading:

- Uncommon words
- Difficult scripts and typefaces 
- Tiny Fonts
- Text on noisy background
- Visual noise from too much text
- Centered text is hard for eyes to follow

Any combination of the above can make for a very unreadable design Support both
reading styles by avoiding the problems listed above.

### Most reading is unnecessary

Most software has too much text in the instructions and people don't read it
anyway. You can be just as clear with less text. Provide a brief overview and
let users request more detail if they want. 

# Chapter 5

## Our Color Vision is Limited

### Optimized for Edge Contrast

We can see something better if it is high contrast and brightness isn't as
important

### Discrimination based on Presentation

The paler (less saturated) two colors are, the harder it is to tell them apart

The smaller and thinner objects are, the harder it is to distinguish their
colors

The more separated color patches are, the more difficult it is to distinguish
their colors

### Color-Blindness

Converting an image to grayscale can help you design applications for color
blind people

### External Factors

Each color display can show something different just because of the technology.
Grayscale displays can also have this problem. Display angle can make different
images look different. TN panels lol. Ambient illumination can wash out colors,
enough to make color displays into grayscale

### Guidelines for using Color

- Distinguish colors by saturation and brightness as well as hue, avoid subtle
  color differences
- Use distinctive colors, increase contrast
- Avoid color pairs that color-blind people cannot distinguish
- Use color redundantly with other hues
- Separate string opponent colors

# Chapter 6

## Our Peripheral Vision is Poor

### Resolution of the Fovea vs Periphery

There is a lower resolution on the outside of your eye than on the inside of
your eye. You see great in the center and not so great on the outsides. We can
discriminate colors better in the center as well.

### Good for Anything?

It provides low resolution cues to help guide our eyes. It sees fuzzy things
and then we focus on that fuzzy thing if it looks like what we want. Its good
at detecting motion

### Computer User Interfaces

Errors are often missed if they aren't placed in the center or where the user
is looking. Make sure error messages are popping up where the user is looking
like the "Login" button.

### Techniques to make messages visible

- Put it where the users are looking (like i said above)
- Mark the error with what it is referencing
- Use an error symbol because people recognize it
- Reserve red for errors because people recognize it

#### More dangerous ways to get user's attention

- Pop-up message

This makes it hard to miss because it steals the focus from the application
window so the user HAS to see it.

- Use Sound
- Flash or Wiggle

These two will alert the user better because they are such obvious indicators
of action. They will cause the user to scan for the error These should be
reserved for very critical errors as they can become very annoying
